#!/usr/bin/env python3

import argparse
import subprocess
import requests
import json
import os
import sys
import shutil
from datetime import datetime

def run_command(command, check=True):
    """Run a shell command and return the result."""
    try:
        result = subprocess.run(command, shell=True, capture_output=True, text=True, check=check)
        return result.stdout.strip()
    except subprocess.CalledProcessError as e:
        print(f"Error running command: {command}")
        print(f"Error: {e.stderr}")
        return None

def create_branch(branch_name):
    """Create a new branch from main."""
    print(f"Creating branch: {branch_name}")
    
    # Ensure we're on main and up to date
    run_command("git checkout main")
    run_command("git pull origin main")
    
    # Create and checkout new branch
    run_command(f"git checkout -b {branch_name}")
    return True

def call_amazon_q_agent(prompt):
    """Call Amazon Q CLI agent with the given prompt."""
    print(f"Calling Amazon Q agent with prompt: {prompt}")
    
    # This is a placeholder - replace with actual Amazon Q CLI command
    # Example: aws q generate-code --prompt "your prompt here"
    command = f'q chat "update files to do the following: {prompt}" --no-interactive --trust-all-tools'
    
    try:
        # Run the command and show output in real-time
        result = subprocess.run(command, shell=True, text=True, check=True)
        print("Amazon Q agent response received")
        return True
    except subprocess.CalledProcessError as e:
        print(f"Failed to get response from Amazon Q agent: {e}")
        return None

def commit_changes(commit_message):
    """Commit any changes made by the agent."""
    print("Committing changes...")
    
    # Add all changes
    run_command("git add .")
    
    # Commit with the provided message
    run_command(f'git commit -m "{commit_message}"')
    return True

def push_branch(branch_name):
    """Push the branch to GitHub."""
    print(f"Pushing branch {branch_name} to GitHub...")
    
    result = run_command(f"git push origin {branch_name}")
    return result is not None

def push_current_branch():
    """Push the current branch to GitHub."""
    current_branch = run_command("git branch --show-current")
    if not current_branch:
        print("Error: Could not determine current branch")
        return False
    
    print(f"Pushing current branch {current_branch} to GitHub...")
    result = run_command(f"git push origin {current_branch}")
    return result is not None

def create_pull_request(branch_name, title, repo_owner, repo_name):
    """Create a pull request using GitHub CLI."""
    print(f"Creating pull request for branch: {branch_name}")
    
    try:
        # Use GitHub CLI to create pull request
        command = f'gh pr create --title "{title}" --body "Changes generated by Amazon Q agent: {title}" --base main --head {branch_name}'
        result = run_command(command)
        
        if result:
            print(f"Pull request created successfully!")
            # Extract PR URL from gh output
            if "https://github.com" in result:
                pr_url = result.strip()
                print(f"PR URL: {pr_url}")
                return pr_url
            else:
                print("Pull request created but couldn't extract URL")
                return True
        else:
            print("Failed to create pull request")
            return None
        
    except Exception as e:
        print(f"Error creating pull request: {e}")
        print("Note: Make sure GitHub CLI (gh) is installed and authenticated.")
        return None

def get_github_info():
    """Extract GitHub repository info from git remote."""
    remote_url = run_command("git remote get-url origin")
    if not remote_url:
        print("Error: Could not get git remote URL")
        return None, None
    
    # Handle both HTTPS and SSH URLs
    if remote_url.startswith("https://"):
        # https://github.com/owner/repo.git
        parts = remote_url.replace("https://github.com/", "").replace(".git", "").split("/")
    else:
        # git@github.com:owner/repo.git
        parts = remote_url.replace("git@github.com:", "").replace(".git", "").split("/")
    
    if len(parts) >= 2:
        return parts[0], parts[1]
    else:
        print("Error: Could not parse GitHub repository info")
        return None, None

def update_command(prompt, commit_message):
    """Update command: call Amazon Q agent and push changes to current branch."""
    print("🔄 Update mode: Working on current branch")
    
    # Check if we're in a git repository
    if not run_command("git rev-parse --git-dir"):
        print("Error: Not in a git repository")
        return False
    
    # Check if we have uncommitted changes
    status = run_command("git status --porcelain")
    if status:
        print("Warning: You have uncommitted changes. Consider committing them first.")
        response = input("Continue anyway? (y/N): ")
        if response.lower() != 'y':
            print("Update cancelled")
            return False
    
    try:
        # Step 1: Call Amazon Q agent
        agent_response = call_amazon_q_agent(prompt)
        if not agent_response:
            print("Failed to get response from Amazon Q agent")
            return False
        
        # Step 2: Check if any changes were made
        status_after = run_command("git status --porcelain")
        if not status_after:
            print("No changes detected after Amazon Q agent response")
            return True
        
        # Step 3: Commit changes
        if not commit_changes(commit_message):
            print("Failed to commit changes")
            return False
        
        # Step 4: Push to current branch
        if not push_current_branch():
            print("Failed to push changes")
            return False
        
        print("✅ Update completed successfully!")
        return True
        
    except KeyboardInterrupt:
        print("\nUpdate cancelled by user")
        return False
    except Exception as e:
        print(f"Unexpected error during update: {e}")
        return False

def create_command(prompt, branch_name, commit_message):
    """Create command: full workflow with new branch and PR."""
    print("🆕 Create mode: Creating new branch and pull request")
    
    # Get GitHub repository info
    repo_owner, repo_name = get_github_info()
    if not repo_owner or not repo_name:
        return False
    
    try:
        # Step 1: Create new branch
        if not create_branch(branch_name):
            print("Failed to create branch")
            return False
        
        # Step 2: Call Amazon Q agent
        agent_response = call_amazon_q_agent(prompt)
        if not agent_response:
            print("Failed to get response from Amazon Q agent")
            return False
        
        # Step 3: Commit changes
        if not commit_changes(commit_message):
            print("Failed to commit changes")
            return False
        
        # Step 4: Push branch
        if not push_branch(branch_name):
            print("Failed to push branch")
            return False
        
        # Step 5: Create pull request using commit message as title
        pr_url = create_pull_request(branch_name, commit_message, repo_owner, repo_name)
        
        if pr_url:
            print(f"\n✅ Success! Pull request created: {pr_url}")
            return True
        else:
            print("Failed to create pull request")
            return False
            
    except KeyboardInterrupt:
        print("\nOperation cancelled by user")
        return False
    except Exception as e:
        print(f"Unexpected error: {e}")
        return False

def read_raml_file():
    """Read the API.raml file and return its contents."""
    try:
        with open('./temp/api.raml', 'r', encoding='utf-8') as file:
            return file.read()
    except FileNotFoundError:
        print("Warning: api.raml file not found")
        return None
    except Exception as e:
        print(f"Error reading api.raml file: {e}")
        return None

def mulesoft_migr_command(prompt, endpoint, branch_name, commit_message):
    """Mulesoft migration command: full workflow with new branch and PR."""
    print("🔄 Mulesoft Migration mode: Creating new branch and pull request")
    
    # Get GitHub repository info
    repo_owner, repo_name = get_github_info()
    if not repo_owner or not repo_name:
        return False
    
    try:
        # Step 1: Create new branch
        if not create_branch(branch_name):
            print("Failed to create branch")
            return False
        
        # Step 2: Download project from Anypoint Design Center
        print("Downloading project from Anypoint Design Center...")
        download_result = run_command("anypoint-cli designcenter project download gen-ai-poc ./temp")
        if not download_result:
            print("Warning: Failed to download project from Anypoint Design Center")
        
        # Step 3: Read API.raml file
        print("Reading API.raml file...")
        raml_content = read_raml_file()
        
        # Step 4: Call Amazon Q agent with endpoint and RAML context
        if raml_content:
            enhanced_prompt = f"""Migrate the following Mulesoft endpoint to python: {endpoint}

API Specification (RAML):
{raml_content}

Additional requirements: {prompt}"""
        else:
            enhanced_prompt = f"Migrate the following Mulesoft endpoint to AWS: {endpoint}. {prompt}"
        
        print("Calling Amazon Q agent with RAML specification...")
        agent_response = call_amazon_q_agent(enhanced_prompt)
        if not agent_response:
            print("Failed to get response from Amazon Q agent")
            return False
        
        # Step 5: Clean up temp folder
        print("Cleaning up temporary files...")
        try:
            if os.path.exists('./temp'):
                shutil.rmtree('./temp')
                print("Temp folder deleted successfully")
        except Exception as e:
            print(f"Warning: Failed to delete temp folder: {e}")
        
        # Step 6: Commit changes
        if not commit_changes(commit_message):
            print("Failed to commit changes")
            return False
        
        # Step 7: Push branch
        if not push_branch(branch_name):
            print("Failed to push branch")
            return False
        
        # Step 8: Create pull request
        pr_url = create_pull_request(branch_name, commit_message, repo_owner, repo_name)
        
        if pr_url:
            print(f"\n✅ Success! Mulesoft migration pull request created: {pr_url}")
            return True
        else:
            print("Failed to create pull request")
            return False
            
    except KeyboardInterrupt:
        print("\nOperation cancelled by user")
        return False
    except Exception as e:
        print(f"Unexpected error: {e}")
        return False

def main():
    parser = argparse.ArgumentParser(description="CLI tool to work with Amazon Q agent and GitHub")
    subparsers = parser.add_subparsers(dest='command', help='Available commands')
    
    # Create command (original functionality)
    create_parser = subparsers.add_parser('create', help='Create new branch, call Amazon Q agent, and create PR')
    create_parser.add_argument("prompt", help="The prompt to send to Amazon Q agent")
    create_parser.add_argument("--branch-name", help="Name for the new branch (default: auto-generated)")
    create_parser.add_argument("--pr-title", help="PR title and commit message (default: auto-generated)")
    
    # Update command (new functionality)
    update_parser = subparsers.add_parser('update', help='Call Amazon Q agent and push changes to current branch')
    update_parser.add_argument("prompt", help="The prompt to send to Amazon Q agent")
    update_parser.add_argument("--commit-message", help="Commit message (default: auto-generated)")
    
    # Mulesoft migration command
    mulesoft_parser = subparsers.add_parser('mulesoft-migr', help='Migrate Mulesoft endpoint to AWS with Amazon Q agent')
    mulesoft_parser.add_argument("endpoint", help="The Mulesoft endpoint to migrate")
    mulesoft_parser.add_argument("prompt", help="Additional prompt for the Amazon Q agent")
    mulesoft_parser.add_argument("--branch-name", help="Name for the new branch (default: auto-generated)")
    mulesoft_parser.add_argument("--pr-title", help="PR title and commit message (default: auto-generated)")
    
    args = parser.parse_args()
    
    if not args.command:
        parser.print_help()
        return
    
    if args.command == 'update':
        # Generate commit message if not provided
        commit_message = args.commit_message or f"Update from Amazon Q agent: {args.prompt[:50]}..."
        
        success = update_command(args.prompt, commit_message)
        sys.exit(0 if success else 1)
    
    elif args.command == 'create':
        # Generate values if not provided
        branch_name = args.branch_name or f"feature/amazon-q-{datetime.now().strftime('%Y%m%d-%H%M%S')}"
        commit_message = args.pr_title or f"Feature: {args.prompt[:50]}..."
        
        success = create_command(args.prompt, branch_name, commit_message)
        sys.exit(0 if success else 1)
    
    elif args.command == 'mulesoft-migr':
        # Generate values if not provided
        branch_name = args.branch_name or f"mulesoft-migration-{datetime.now().strftime('%Y%m%d-%H%M%S')}"
        commit_message = args.pr_title or f"Mulesoft Migration: {args.endpoint[:50]}..."
        
        success = mulesoft_migr_command(args.prompt, args.endpoint, branch_name, commit_message)
        sys.exit(0 if success else 1)

if __name__ == "__main__":
    main() 